#!/usr/bin/env python3
"""
Embedding Extraction Script for hIPSC_CM dataset using MIMIC (Frozen Encoder)
=============================================================================
This script:
1. Loads the precomputed hIPSC_CM dataset exclusively from Parquet:
   /beegfs/prj/RNA_NLP/FlorianMasterThesis/code/data/hIPSC_CM/hIPSC_CM_mrna_protein.parquet
   (Generated by reconstruct_proteins_hIPSC_CM.py; strictly no fallbacks).
2. Reads precomputed clean RNA sequences (clean_rna_seq), protein sequences (protein_seq_clean),
   and CDS tracks (cds) directly from Parquet.
3. Supports 3 embedding modes (for training 3 downstream Ridge Regressions):
   - 'rna': Uses only RNA nucleotide sequence (clean_rna_seq) -> 9216-dim embedding.
   - 'protein': Uses only reconstructed protein sequence (protein_seq_clean) -> 9216-dim embedding.
   - 'rna_protein': Joint multimodal conditioning (clean_rna_seq + protein_seq_clean) -> 10752-dim embedding.
   - 'all': Generates all 3 sets of embeddings in one run!
4. Saves all embeddings and metadata in compressed NPZ archives at:
   /beegfs/prj/RNA_NLP/FlorianMasterThesis/code/data/hIPSC_CM/mimic/
   - mimic_embeddings_hIPSC_CM_rna.npz
   - mimic_embeddings_hIPSC_CM_protein.npz
   - mimic_embeddings_hIPSC_CM_rna_protein.npz

Usage:
------
# 1. Generate all 3 embedding sets in one run:
python scripts/extract_embeddings_hIPSC_CM.py --mode all

# 2. Or generate individual modes:
python scripts/extract_embeddings_hIPSC_CM.py --mode rna
python scripts/extract_embeddings_hIPSC_CM.py --mode protein
python scripts/extract_embeddings_hIPSC_CM.py --mode rna_protein

# Optional: With local weights directory:
python scripts/extract_embeddings_hIPSC_CM.py --mode all --weights_dir /path/to/mimic_weights
"""

import os
import sys
import argparse
import time
from pathlib import Path
from typing import List, Dict, Tuple, Optional

import numpy as np
import pandas as pd
import torch
from tqdm import tqdm

from util import reset_peak_memory_stats, print_memory_profile

# Ensure local mimic package is on sys.path if run from within repo or scripts dir
SCRIPT_DIR = Path(__file__).resolve().parent
REPO_ROOT = SCRIPT_DIR.parent
if str(REPO_ROOT / "src") not in sys.path:
    sys.path.insert(0, str(REPO_ROOT / "src"))

try:
    from mimic import load_pretrained
except ImportError as e:
    raise ImportError(
        f"Could not import 'mimic'. Please install the package (`pip install -e .`) "
        f"or ensure {REPO_ROOT / 'src'} is in PYTHONPATH. Error: {e}"
    )


# Default Paths on the cluster
# Defaults directly to the pre-reconstructed dataset from reconstruct_proteins_hIPSC_CM.py
DEFAULT_DATA_PATH = "/beegfs/prj/RNA_NLP/FlorianMasterThesis/code/data/hIPSC_CM/hIPSC_CM_mrna_protein.parquet"
DEFAULT_OUTPUT_DIR = "/beegfs/prj/RNA_NLP/FlorianMasterThesis/code/data/hIPSC_CM/mimic"





def build_batches_by_length(
    samples: List[Dict],
    mode: str = "rna",
    batch_size: int = 4,
    max_tokens_per_batch: int = 24000,
) -> List[List[Dict]]:
    """
    Groups samples into batches by active sequence length to minimize padding waste.
    """
    def sample_len(s: Dict) -> int:
        if mode == "rna":
            return len(s["rna_seq"])
        elif mode == "protein":
            return len(s["protein_seq"]) if s["has_cds"] else 1
        elif mode == "rna_protein":
            return len(s["rna_seq"]) + (len(s["protein_seq"]) if s["has_cds"] else 0)
        return len(s["rna_seq"])

    sorted_samples = sorted(samples, key=sample_len)

    batches = []
    current_batch = []
    current_max_len = 0

    for s in sorted_samples:
        s_len = max(1, sample_len(s))
        prospective_max_len = max(current_max_len, s_len)
        prospective_tokens = (len(current_batch) + 1) * prospective_max_len

        if len(current_batch) >= batch_size or (current_batch and prospective_tokens > max_tokens_per_batch):
            batches.append(current_batch)
            current_batch = [s]
            current_max_len = s_len
        else:
            current_batch.append(s)
            current_max_len = prospective_max_len

    if current_batch:
        batches.append(current_batch)

    return batches


def extract_embeddings_for_mode(
    samples: List[Dict],
    model: torch.nn.Module,
    mode: str = "rna",
    include_cds: bool = False,
    batch_size: int = 4,
    max_tokens_per_batch: int = 24000,
    desc: str = None,
) -> Dict[str, np.ndarray]:
    """
    Extracts MIMIC embeddings for a given mode ('rna', 'protein', or 'rna_protein').

    Dimensions:
    - 'rna':
        concat_primary: register [5*1536=7680] + rna_mean [1536] = 9216 dim
        rna_mean: 1536 dim
        reg_mean: 1536 dim
    - 'protein':
        concat_primary: register [5*1536=7680] + prot_mean [1536] = 9216 dim
        prot_mean: 1536 dim
        reg_mean: 1536 dim
        (non-coding entries with has_cds=False are set to zeros)
    - 'rna_protein':
        concat_primary: register [7680] + rna_mean [1536] + prot_mean [1536] = 10752 dim
        rna_mean: 1536 dim
        prot_mean: 1536 dim
        reg_mean: 1536 dim
        (non-coding entries use NT sequence and have prot_mean = zeros, matching mRNABench)
    """
    desc = desc or f"Extracting MIMIC Embeddings ({mode})"
    N = len(samples)

    if mode == "rna":
        emb_primary = np.zeros((N, 9216), dtype=np.float32)
        emb_rna_mean = np.zeros((N, 1536), dtype=np.float32)
        emb_prot_mean = None
    elif mode == "protein":
        emb_primary = np.zeros((N, 9216), dtype=np.float32)
        emb_rna_mean = None
        emb_prot_mean = np.zeros((N, 1536), dtype=np.float32)
    elif mode == "rna_protein":
        emb_primary = np.zeros((N, 10752), dtype=np.float32)
        emb_rna_mean = np.zeros((N, 1536), dtype=np.float32)
        emb_prot_mean = np.zeros((N, 1536), dtype=np.float32)
    else:
        raise ValueError(f"Unknown mode '{mode}'")

    emb_reg_mean = np.zeros((N, 1536), dtype=np.float32)

    # For protein mode, filter to coding samples only (cannot pass empty protein sequence)
    if mode == "protein":
        active_samples = [s for s in samples if s["has_cds"] and len(s["protein_seq"]) > 0]
    else:
        active_samples = samples

    batches = build_batches_by_length(
        active_samples, mode=mode, batch_size=batch_size, max_tokens_per_batch=max_tokens_per_batch
    )

    with torch.no_grad():
        for batch in tqdm(batches, desc=desc):
            model_batch = []
            for item in batch:
                inp = {}
                if mode in ("rna", "rna_protein"):
                    inp["rna_seq"] = item["rna_seq"]
                    if include_cds and len(item.get("cds_mask", "")) == len(item["rna_seq"]):
                        inp["cds"] = item["cds_mask"]

                if mode == "protein":
                    inp["aa_seq"] = item["protein_seq"]
                elif mode == "rna_protein":
                    if item["has_cds"] and len(item["protein_seq"]) > 0:
                        inp["aa_seq"] = item["protein_seq"]

                model_batch.append(inp)

            # Stage inputs and forward pass through frozen encoder
            model.input(model_batch)
            reps = model.embed(return_full=True, return_register=True, return_modality=True)

            register_tensor = reps["register"]  # [B, 5, 1536]
            modality_dict = reps["modality"]    # {b_idx: {group_name: Tensor}}

            for b_idx, item in enumerate(batch):
                orig_i = item["orig_idx"]

                # Register representations
                reg_b = register_tensor[b_idx]  # [5, 1536]
                reg_flat = reg_b.flatten().cpu().numpy()  # [7680]
                reg_mean = reg_b.mean(dim=0).cpu().numpy()  # [1536]
                emb_reg_mean[orig_i] = reg_mean

                # RNA track representation
                rna_mean = np.zeros(1536, dtype=np.float32)
                if "dna/rna" in modality_dict[b_idx]:
                    rna_tokens = modality_dict[b_idx]["dna/rna"]
                    rna_mean = rna_tokens.mean(dim=0).cpu().numpy()
                if emb_rna_mean is not None:
                    emb_rna_mean[orig_i] = rna_mean

                # Protein track representation
                prot_mean = np.zeros(1536, dtype=np.float32)
                if "protein" in modality_dict[b_idx]:
                    prot_tokens = modality_dict[b_idx]["protein"]
                    prot_mean = prot_tokens.mean(dim=0).cpu().numpy()
                if emb_prot_mean is not None:
                    emb_prot_mean[orig_i] = prot_mean

                # Combine into primary embedding
                if mode == "rna":
                    emb_primary[orig_i] = np.concatenate([reg_flat, rna_mean], axis=0)  # 9216
                elif mode == "protein":
                    emb_primary[orig_i] = np.concatenate([reg_flat, prot_mean], axis=0)  # 9216
                elif mode == "rna_protein":
                    emb_primary[orig_i] = np.concatenate([reg_flat, rna_mean, prot_mean], axis=0)  # 10752

            if torch.cuda.is_available():
                torch.cuda.empty_cache()

    result = {
        "embeddings": emb_primary,
        "embeddings_reg_mean": emb_reg_mean,
    }
    if emb_rna_mean is not None:
        result["embeddings_rna_mean"] = emb_rna_mean
    if emb_prot_mean is not None:
        result["embeddings_prot_mean"] = emb_prot_mean

    return result


def save_embeddings_npz(
    output_path: Path,
    embeddings_dict: Dict[str, np.ndarray],
    df: pd.DataFrame,
    parsed_samples: List[Dict],
    mode: str,
    model_version: str,
    include_cds: bool,
    max_length: int,
):
    """Saves the extracted embeddings and metadata to an NPZ archive."""
    num_samples = len(df)
    has_cds_array = np.array([s["has_cds"] for s in parsed_samples], dtype=bool)
    rna_lens = np.array([s["rna_len"] for s in parsed_samples], dtype=np.int32)
    prot_lens = np.array([s["prot_len"] for s in parsed_samples], dtype=np.int32)

    half_lives = (
        df["half_life"].astype(np.float32).values
        if "half_life" in df.columns
        else np.full(num_samples, np.nan, dtype=np.float32)
    )
    half_lives_transformed = (
        df["half_life_transformed"].astype(np.float32).values
        if "half_life_transformed" in df.columns
        else np.full(num_samples, np.nan, dtype=np.float32)
    )
    rates = (
        df["rate"].astype(np.float32).values
        if "rate" in df.columns
        else np.full(num_samples, np.nan, dtype=np.float32)
    )
    tx_col = "transcript_id" if "transcript_id" in df.columns else "ensembl_transcript_id"
    transcript_ids = df[tx_col].astype(str).values if tx_col in df.columns else np.array([""] * num_samples)

    gene_col = "gene" if "gene" in df.columns else "hgnc_symbol"
    gene_symbols = df[gene_col].astype(str).values if gene_col in df.columns else np.array([""] * num_samples)

    gene_ids = (
        df["ensembl_gene_id"].astype(str).values
        if "ensembl_gene_id" in df.columns
        else np.array([""] * num_samples)
    )
    biotypes = (
        df["transcript_biotype"].astype(str).values
        if "transcript_biotype" in df.columns
        else np.array([""] * num_samples)
    )

    save_dict = {
        "embeddings": embeddings_dict["embeddings"],
        "embeddings_reg_mean": embeddings_dict["embeddings_reg_mean"],
        "half_life": half_lives,
        "half_life_transformed": half_lives_transformed,
        "rate": rates,
        "ensembl_transcript_id": transcript_ids,
        "ensembl_gene_id": gene_ids,
        "hgnc_symbol": gene_symbols,
        "transcript_biotype": biotypes,
        "seq_lens": rna_lens,
        "prot_lens": prot_lens,
        "has_cds": has_cds_array,
        "mode": str(mode),
        "model_version": str(model_version),
        "include_cds": bool(include_cds),
        "max_length": int(max_length),
    }

    if "split" in df.columns:
        save_dict["split"] = df["split"].values

    if "embeddings_rna_mean" in embeddings_dict:
        save_dict["embeddings_rna_mean"] = embeddings_dict["embeddings_rna_mean"]
    if "embeddings_prot_mean" in embeddings_dict:
        save_dict["embeddings_prot_mean"] = embeddings_dict["embeddings_prot_mean"]

    output_path.parent.mkdir(parents=True, exist_ok=True)
    print(f"\nSaving NPZ archive to: {output_path} ...")
    np.savez_compressed(output_path, **save_dict)
    print(f"[✓] Successfully saved:")
    print(f"    File:             {output_path}")
    print(f"    Mode:             {mode}")
    print(f"    Embedding Shape:  {embeddings_dict['embeddings'].shape}")


def main():
    parser = argparse.ArgumentParser(
        description="Extract MIMIC frozen encoder embeddings (RNA, Protein, or Joint RNA+Protein) for hIPSC_CM dataset"
    )
    parser.add_argument(
        "--data_path",
        type=str,
        default=DEFAULT_DATA_PATH,
        help=f"Path to hIPSC_CM transformed dataset (default: {DEFAULT_DATA_PATH})",
    )
    parser.add_argument(
        "--output_dir",
        type=str,
        default=DEFAULT_OUTPUT_DIR,
        help=f"Directory to save embeddings (default: {DEFAULT_OUTPUT_DIR})",
    )
    parser.add_argument(
        "--output_filename",
        type=str,
        default=None,
        help="Custom filename for the NPZ archive (defaults to mimic_embeddings_hIPSC_CM_<mode>.npz)",
    )
    parser.add_argument(
        "--mode",
        type=str,
        default="rna",
        choices=["rna", "protein", "rna_protein", "all"],
        help="Which modality representation to generate: 'rna', 'protein', 'rna_protein', or 'all' (default: rna)",
    )
    parser.add_argument(
        "--model_version",
        type=str,
        default="1.0",
        help="MIMIC model version to download/load (default: 1.0)",
    )
    parser.add_argument(
        "--weights_dir",
        type=str,
        default=None,
        help="Optional local path to weights directory containing config.json and model.safetensors",
    )
    parser.add_argument(
        "--batch_size",
        type=int,
        default=4,
        help="Max batch size for inference (default: 4)",
    )
    parser.add_argument(
        "--max_tokens_per_batch",
        type=int,
        default=24000,
        help="Max total tokens in a single batch to avoid VRAM overflow (default: 24000)",
    )
    parser.add_argument(
        "--max_length",
        type=int,
        default=10000,
        help="Maximum sequence length for MIMIC (default: 10000)",
    )
    parser.add_argument(
        "--include_cds",
        action="store_true",
        help="If set, also includes the binary CDS mask modality alongside rna_seq in the RNA track",
    )
    args = parser.parse_args()

    data_path = Path(args.data_path)
    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    # Determine execution device: always prefer CUDA if available
    selected_device = "cuda" if torch.cuda.is_available() else "cpu"
    reset_peak_memory_stats(selected_device)

    device_str = f"CUDA ({torch.cuda.get_device_name(0)})" if selected_device == "cuda" else "CPU"

    print("=" * 75)
    print("        MIMIC Multimodal Embedding Pipeline for hIPSC_CM        ")
    print("=" * 75)
    print(f"Data file:             {data_path}")
    print(f"Output directory:      {output_dir}")
    print(f"Extraction Mode:       {args.mode.upper()}")
    print(f"MIMIC Version:         {args.model_version}")
    print(f"Local Weights:         {args.weights_dir or 'Hugging Face Hub (polymathic-ai/MIMIC)'}")
    print(f"Device:                {device_str}")
    print(f"Batch size:            {args.batch_size} (max {args.max_tokens_per_batch} tokens/batch)")
    print(f"Max sequence len:      {args.max_length}")

    # 1. Load Data
    print(f"\n[1/4] Loading dataset...")
    if not data_path.exists():
        raise FileNotFoundError(
            f"Mandatory dataset Parquet file not found: '{data_path}'. "
            f"This script exclusively expects the precomputed Parquet file: '{DEFAULT_DATA_PATH}'. "
            f"Please run 'reconstruct_proteins_hIPSC_CM.py' first!"
        )

    if data_path.suffix.lower() != ".parquet":
        raise ValueError(
            f"Invalid file format '{data_path.suffix}'. "
            f"This script exclusively accepts Parquet files (.parquet) at '{DEFAULT_DATA_PATH}'. "
            f"No fallbacks (e.g. .tsv or .txt) are supported."
        )

    print(f"Loading from Parquet: {data_path}")
    df = pd.read_parquet(data_path)
    num_samples = len(df)
    print(f"Loaded {num_samples} transcripts. Columns: {list(df.columns)}")

    # Strict check for required precomputed columns
    REQUIRED_COLUMNS = [
        "clean_rna_seq",
        "protein_seq_clean",
        "has_cds",
        "cds",
        "transcript_id",
        "gene",
        "half_life_transformed",
    ]
    missing_cols = [c for c in REQUIRED_COLUMNS if c not in df.columns]
    if missing_cols:
        raise KeyError(
            f"Dataset '{data_path}' is missing mandatory column(s): {missing_cols}. "
            f"Present columns: {list(df.columns)}. "
            f"Please regenerate the file with 'reconstruct_proteins_hIPSC_CM.py'."
        )

    # 2. Prepare sequences from precomputed Parquet
    print(f"\n[2/4] Reading precomputed sequences and proteins from '{data_path.name}'...")
    parsed_samples = []
    truncated_count = 0

    for idx, row in tqdm(df.iterrows(), total=num_samples, desc="Loading precomputed sequences"):
        rna_seq = str(row["clean_rna_seq"]).strip()
        if not rna_seq:
            raise ValueError(
                f"Empty RNA sequence found at row {idx} (transcript: {row.get('transcript_id', '')})!"
            )

        orig_len = len(rna_seq)
        if orig_len > args.max_length:
            truncated_count += 1
            rna_seq = rna_seq[: args.max_length]

        prot_seq = str(row["protein_seq_clean"]).strip() if pd.notna(row["protein_seq_clean"]) else ""
        if prot_seq.lower() in ("nan", "none"):
            prot_seq = ""

        has_cds = bool(row["has_cds"]) and len(prot_seq) > 0

        # CDS binary track (used if --include_cds is set)
        cds_mask = str(row["cds"]).strip() if pd.notna(row["cds"]) else ""
        if len(cds_mask) > args.max_length:
            cds_mask = cds_mask[: args.max_length]

        parsed_samples.append({
            "orig_idx": idx,
            "rna_seq": rna_seq,
            "cds_mask": cds_mask,
            "protein_seq": prot_seq,
            "has_cds": has_cds,
            "orig_len": orig_len,
            "rna_len": len(rna_seq),
            "prot_len": len(prot_seq),
        })

    if truncated_count > 0:
        print(f"Notice: {truncated_count} transcripts exceeded {args.max_length} nt and were truncated.")

    coding_count = sum(1 for s in parsed_samples if s["has_cds"])
    print(f"Total transcripts:         {num_samples}")
    print(f"Coding transcripts (CDS):   {coding_count} ({coding_count / num_samples * 100:.1f}%)")
    print(f"Non-coding transcripts:    {num_samples - coding_count} ({(num_samples - coding_count) / num_samples * 100:.1f}%)")

    # 3. Load MIMIC Model
    print(f"\n[3/4] Loading pretrained MIMIC model (Frozen Encoder)...")
    t0 = time.time()
    model = load_pretrained(
        version=args.model_version,
        local_path=args.weights_dir,
        device=selected_device,
    )
    model.freeze_encoder(freeze_embeddings=True)
    model.eval()
    print(f"Model loaded successfully in {time.time() - t0:.2f}s on {model.device}.")

    # 4. Extract Embeddings for selected mode(s)
    print(f"\n[4/4] Running embedding extraction...")
    modes_to_run = ["rna", "protein", "rna_protein"] if args.mode == "all" else [args.mode]

    for mode in modes_to_run:
        print("\n" + "-" * 60)
        print(f"   Executing Mode: {mode.upper()}")
        print("-" * 60)

        t_start = time.time()
        embs_dict = extract_embeddings_for_mode(
            samples=parsed_samples,
            model=model,
            mode=mode,
            include_cds=args.include_cds,
            batch_size=args.batch_size,
            max_tokens_per_batch=args.max_tokens_per_batch,
            desc=f"Extracting MIMIC Embeddings ({mode})",
        )
        elapsed = time.time() - t_start
        print(f"Extraction for mode '{mode}' done in {elapsed:.2f}s ({elapsed / num_samples:.4f}s / sample).")

        # Determine output filename
        if args.output_filename and len(modes_to_run) == 1:
            save_name = args.output_filename
        else:
            save_name = f"mimic_embeddings_hIPSC_CM_{mode}.npz"

        out_file = output_dir / save_name
        save_embeddings_npz(
            output_path=out_file,
            embeddings_dict=embs_dict,
            df=df,
            parsed_samples=parsed_samples,
            mode=mode,
            model_version=args.model_version,
            include_cds=args.include_cds,
            max_length=args.max_length,
        )

    print("\n" + "=" * 75)
    print(" [✓] All requested MIMIC embeddings successfully extracted and saved!")
    print("=" * 75)

    print_memory_profile(device=selected_device, title="MIMIC EMBEDDINGS SPEICHER-PROFILING")


if __name__ == "__main__":
    main()
